name: build and test

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
      - '**.cs'
      - '**.csproj'

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}-${{matrix.dotnet}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        dotnet: [ 8.0.X, 9.0.X ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
          global-json-file: global.json

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-restore

      - name: Publish
        run: dotnet publish src/ConventionalChangelog/ConventionalChangelog.csproj --framework net8.0 --configuration
          Release --output release --nologo

      - name: Upload Build Artifact
        if: matrix.dotnet == '9.0.X'
        uses: actions/upload-artifact@v4
        with:
          name: Application_${{ matrix.os }}
          path: release
